CREATE TABLE IF NOT EXISTS champions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    lore TEXT,
    image_url VARCHAR(255)
    );

INSERT INTO champions (name, role, lore, image_url) VALUES
    ('Brimstone', 'Controlador', 'Vindo diretamente dos EUA, o arsenal orbital do Brimstone garante que o esquadrao dele sempre esteja em vantagem. Sua capacidade de oferecer utilitarios com precisao e seguranca faz dele um comandante inigualavel na linha de frente.', 'https://theclutch.com.br/wp-content/uploads/2022/03/brimstone-valorant.jpg'),
    ('Phoenix', 'Duelista', 'Chegando com tudo diretamente do Reino Unido, o poder estelar de Phoenix reluz em seu estilo de luta, incendiando o campo de batalha com luz e estilo. Tendo ajuda ou nao, ele entra na luta como e quando achar que deve.', 'https://prod.assets.earlygamecdn.com/images/VALORANT-Phoenix-Light.jpg'),
    ('Sage', 'Sentinela', 'Como uma verdadeira fortaleza chinesa, Sage traz seguranca para si mesma e para a equipe aonde quer que va. Capaz de reviver aliados e rechacar investidas agressivas, ela oferece um centro de calmaria em meio ao caos da batalha.', 'https://theclutch.com.br/wp-content/uploads/2023/03/sage-valorant.jpg'),
    ('Sova', 'Iniciador', 'Nascido sob o eterno inverno das tundras russas, Sova rastreia, encontra e elimina inimigos com eficiencia e precisao implacaveis. Seu arco personalizado e suas habilidades inigualaveis de reconhecimento garantem que nenhuma presa escape.', 'https://theclutch.com.br/wp-content/uploads/2023/03/sova-valorant-1160x653.jpg'),
    ('Viper', 'Controladora', 'Viper, a quimica dos Estados Unidos, emprega uma variedade de dispositivos quimicos venenosos para controlar o campo de batalha e prejudicar a visao do inimigo. Se as toxinas nao matarem a presa, seus jogos mentais certamente o farao.', 'https://theclutch.com.br/wp-content/uploads/2020/04/VALORANT_VIPER_2-1.jpg'),
    ('Cypher', 'Sentinela', 'Cypher, um vendedor de informacoes do Marrocos, e uma verdadeira rede de vigilancia de um homem so que fica de olho em cada movimento dos inimigos. Nenhum segredo esta a salvo. Nenhuma manobra passa despercebida. Cypher esta sempre vigiando.', 'https://theclutch.com.br/wp-content/uploads/2023/03/cypher-valorant-1160x653.jpg'),
    ('Reyna', 'Duelista', 'Criada no coracao do Mexico, Reyna domina o combate individual, destacando-se a cada abate efetuado. Sua capacidade so e limitada por sua propria pericia, tornando-a bastante dependente de desempenho.', 'https://theclutch.com.br/wp-content/uploads/2021/02/Valorant-Reyna-1-1068x601.jpg'),
    ('Killjoy', 'Sentinela', 'Killjoy, uma alema genial, defende posicoes-chave no campo de batalha facilmente com seu arsenal de invencoes. Se o dano causado por seu equipamento nao der cabo dos inimigos, os efeitos negativos de seus queridos robos darao conta do recado.', 'https://theclutch.com.br/wp-content/uploads/2023/03/killjoy-valorant-1160x653.jpg'),
    ('Breach', 'Iniciador', 'Breach, o homem-bionico sueco, dispara poderosos jatos cineticos para forcar a abertura de um caminho pelo territorio inimigo. O dano e a interrupcao que ele causa garantem que nenhuma luta seja justa.', 'https://theclutch.com.br/wp-content/uploads/2020/09/18c90236-thumb-1920-1080938-1068x601.jpg'),
    ('Omen', 'Controlador', 'Omen, uma lembranca fantasmagorica, caca nas sombras. Ele cega os inimigos, teleporta-se pelo campo e deixa a paranoia assumir o controle enquanto o adversario tenta descobrir de onde vira seu proximo ataque.', 'https://theclutch.com.br/wp-content/uploads/2023/03/omen-valorant-1160x653.jpg'),
    ('Jett', 'Duelista', 'Representando a Coreia do Sul, sua terra natal, Jett tem um estilo de luta agil e evasivo que permite que ela assuma riscos como ninguem. Ela corre em meio a qualquer confronto, cortando os inimigos antes mesmo que eles percebam quem ou o que os atingiu.', 'https://theclutch.com.br/wp-content/uploads/2023/03/jett-valorant-1160x653.jpg'),
    ('Raze', 'Duelista', 'Raze chega do Brasil com uma explosao de carisma e armas enormes. Com seu estilo de jogo "porradeiro", ela e craque em desentocar inimigos entrincheirados e limpar espacos apertados com uma bela dose de BUUUM!', 'https://theclutch.com.br/wp-content/uploads/2023/03/raze-valorant-1160x653.jpg'),
    ('Skye', 'Iniciadora', 'Mandando um salve direto da Australia, Skye e sua equipe de feras desbravam territorios hostis. Com seus poderes de cura e suas criacoes que partem pra cima dos inimigos, qualquer equipe ficara mais forte e mais segura tendo Skye como aliada.', 'https://theclutch.com.br/wp-content/uploads/2023/03/skye-valorant-1160x653.jpg'),
    ('Yoru', 'Duelista', 'Yoru, nativo do Japao, abre fendas na realidade para infiltrar as linhas inimigas sem ser visto. Ele usa tanto artimanhas quanto taticas agressivas, e os alvos sao abatidos sem saber de onde o ataque veio.', 'https://theclutch.com.br/wp-content/uploads/2023/03/yoru-valorant-1160x653.jpg'),
    ('Astra', 'Controladora', 'Astra, a Agente ganense, utiliza energias cosmicas para moldar o campo de batalha a seu bel-prazer. Com total dominio da sua forma astral e um talento estrategico nato, ela esta sempre anos-luz a frente dos inimigos.', 'https://theclutch.com.br/wp-content/uploads/2023/03/astra-valorant-1160x653.jpg'),
    ('Kay/O', 'Iniciador', 'KAY/O e uma maquina de guerra construída com um unico proposito: neutralizar Radiantes. Ele e capaz de Suprimir habilidades inimigas, anulando a capacidade de contra-ataque dos adversários e dando a si e a seus aliados uma vantagem essencial em combate.', 'https://theclutch.com.br/wp-content/uploads/2023/03/kayo-valorant-1160x653.jpg'),
    ('Chamber', 'Sentinela', 'Bem-vestido e armado ate os dentes, o criador de armas frances Chamber coloca os inimigos para correr com precisao mortal. Use e abuse do arsenal personalizado dele para segurar posicoes e abater inimigos de longe, criando a defesa perfeita para qualquer plano.', 'https://theclutch.com.br/wp-content/uploads/2021/10/chamber-1068x601.jpg'),
	('Neon', 'Duelista', 'Neon, nossa Agente filipina, avanca em velocidades incriveis, descarregando surtos de radiancia bioeletrica tao rapidamente quanto seu corpo consegue gera-los. Ela corre a frente para pegar os inimigos de surpresa, abatendo-os mais rapido do que um raio.', 'https://theclutch.com.br/wp-content/uploads/2023/03/neon-valorant-1160x653.jpg'),
	('Fade', 'Iniciadora', 'Fade, uma cacadora de recompensas turca, usa o poder dos pesadelos para capturar os segredos dos inimigos. Personificando o proprio terror, ela persegue os alvos e revela seus medos mais profundos para, depois, destrui-los na escuridao.', 'https://theclutch.com.br/wp-content/uploads/2023/03/fade-valorant-1160x653.jpg'),
	('Harbor', 'Controlador', 'Vindo do litoral indiano, Harbor entra em campo com a forca da tormenta, empunhando tecnologia ancestral com dominio sobre a agua. Ele libera corredeiras espumantes e ondas esmagadoras para proteger seus aliados ou atacar aqueles que se opoem a ele.', 'https://theclutch.com.br/wp-content/uploads/2023/03/harbor-valorant-1160x653.jpg'),
	('Gekko', 'Iniciador', 'Gekko, de Los Angeles, lidera um grupo muito unido de criaturas caoticas. Seus amigos atropelam tudo, tirando os inimigos do caminho. Depois, Gekko corre atras deles para reagrupa-los e reiniciar o processo.', 'https://theclutch.com.br/wp-content/uploads/2023/03/gekko-valorant-1160x653.jpg'),
	('Deadlock', 'Sentinela', 'A agente norueguesa Deadlock posiciona uma gama de nanofios de alta tecnologia para proteger o campo de batalha ate mesmo do ataque mais letal. Ninguem escapa do seu olhar vigilante. Ninguem sobrevive a sua ferocidade implacavel.', 'https://theclutch.com.br/wp-content/uploads/2023/06/deadlock-valorant-1160x653.jpg'),
	('Iso', 'Duelista', 'Iso e um mercenario chines que entra em estado de fluxo para desmantelar os oponentes. Ele reconfigura a energia do ambiente para se proteger de balas e avanca totalmente focado em direcao ao proximo duelo ate a morte.', 'https://i.ytimg.com/vi/aL-BcdVE4BA/maxresdefault.jpg'),
	('Clove','Controladora','Clove, ume encrenqueire da Escocia, vai trazer a confusao direto do alem-tumulo. E jovem imortal vai deixar os inimigos completamente perdidos, tanto no calor do combate quanto no frio da morte.','https://cdn.oneesports.gg/cdn-data/2024/03/Valorant_Clove_Agent25_KeyArt-1024x576.jpg');